### PR TITLE
update to 0.9.0

### PR DESCRIPTION
**Pull request by alexanderhudym**
HI!
I was interested in your project and wanted to optimize your wallet application.
add java 8 support
update dependencies
clean up code
rewrite some features
add butter knife

if you like, I'll soon release more add-ons

### CODE REVIEW

**Comment by pinpong** [comment]
Thats a lot. Let me check the patch this weekend. Why did you changed the file permissions?

**Comment by pinpong** [comment]
@alexanderhudym

Why did you changed the file permissions?

**Comment by alexanderhudym** [comment]
@pinpong 
Are you now talking about the travis file?
If so, I did not change it, I cloned it from the repository

**Comment by pinpong** [comment]
No, i'm talking about the file permission changes from 100644 → 100755.

**Comment by alexanderhudym** [comment]
well, I understood what you mean
I did not touch this either when I made the commit
maybe it's because of the creation of a new branch

**Comment by pinpong** [comment]
Please change the file permissions, afterwards i can merge it.

**Comment by pinpong** [comment]
@alexanderhudym 
take a look at this [link](https://github.com/Gizra/KnowledgeBase/wiki/How-to-set-Git-to-ignore-chmod-changes)

**Pull request merged**
